# typed: false
# frozen_string_literal: true

# Generated by goreleaser on release. Do not edit by hand: the next release
# overwrites this file, so an edit survives only until then and disagrees with
# the published archives in the meantime.
class Belay < Formula
  desc "Durable, resumable orchestrator for autonomous coding agents"
  homepage "https://github.com/dhaam-ai/belay"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhaam-ai/belay/releases/download/v0.1.1/belay_0.1.1_darwin_arm64.tar.gz"
      sha256 "ac4d7d0e5c974f16c6bf09f65446575d015f4a4573d66c161687119a7aa1c287"
    else
      url "https://github.com/dhaam-ai/belay/releases/download/v0.1.1/belay_0.1.1_darwin_amd64.tar.gz"
      sha256 "4d5bd0096adde5978f5169cb95c0c40a372f49ab34e69455e07ae20198b4baf4"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/dhaam-ai/belay/releases/download/v0.1.1/belay_0.1.1_linux_arm64.tar.gz"
      sha256 "d2ad2deb86a26a033e64a1703530c3c811cda7bbea178fc11394b4f978d1c520"
    else
      url "https://github.com/dhaam-ai/belay/releases/download/v0.1.1/belay_0.1.1_linux_amd64.tar.gz"
      sha256 "25ccddfd6a25896e6f77de913d4871372c19b674324b5e0caac1718636ce07b8"
    end
  end

  def install
    bin.install "belay"
  end

  def caveats
    <<~EOS
      belay drives an agent CLI; it is not one. Install Claude Code and sign in:

        https://claude.com/product/claude-code

      Then, in a repository you want it to work on:

        belay --dry-run run "add tests for the config parser"

      The dry run creates nothing and spends nothing. Drop --dry-run to start.
      belay stops at the plan for you to read before it writes any code.
    EOS
  end

  test do
    assert_match "belay version", shell_output("#{bin}/belay version")
  end
end
