# typed: false
# frozen_string_literal: true

# Generated by goreleaser on release. Do not edit by hand: the next release
# overwrites this file, so an edit survives only until then and disagrees with
# the published archives in the meantime.
class Belay < Formula
  desc "Durable, resumable orchestrator for autonomous coding agents"
  homepage "https://github.com/dhaam-ai/belay"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhaam-ai/belay/releases/download/v0.1.3/belay_0.1.3_darwin_arm64.tar.gz"
      sha256 "3d2028443a78602c5e47a2d92156f3523277ea956982a943c01e4628d5874724"
    else
      url "https://github.com/dhaam-ai/belay/releases/download/v0.1.3/belay_0.1.3_darwin_amd64.tar.gz"
      sha256 "ad5aba736f57789e8425dd510b72ec8f82f543fc68073e1265021850729d87df"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/dhaam-ai/belay/releases/download/v0.1.3/belay_0.1.3_linux_arm64.tar.gz"
      sha256 "1b1e36419769ff24cf08d601a8fee281553c2ff83d7cad775c78e7e0a915a780"
    else
      url "https://github.com/dhaam-ai/belay/releases/download/v0.1.3/belay_0.1.3_linux_amd64.tar.gz"
      sha256 "b831d01fa69397284dc10d93a4fc3c4976fb5f95db67a6293e5745fcf7a3ef38"
    end
  end

  def install
    bin.install "belay"
  end

  def caveats
    <<~EOS
      belay drives an agent CLI; it is not one. Install Claude Code and sign in:

        https://claude.com/product/claude-code

      Then, in a repository you want it to work on:

        belay --dry-run run "add tests for the config parser"

      The dry run creates nothing and spends nothing. Drop --dry-run to start.
      belay stops at the plan for you to read before it writes any code.
    EOS
  end

  test do
    assert_match "belay version", shell_output("#{bin}/belay version")
  end
end
