# typed: false
# frozen_string_literal: true

# Generated by goreleaser on release. Do not edit by hand: the next release
# overwrites this file, so an edit survives only until then and disagrees with
# the published archives in the meantime.
class Belay < Formula
  desc "Durable, resumable orchestrator for autonomous coding agents"
  homepage "https://github.com/dhaam-ai/belay"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhaam-ai/belay/releases/download/v0.1.2/belay_0.1.2_darwin_arm64.tar.gz"
      sha256 "daaa51c22ba57814637ea8f47920ded29cd569d96d0587c3a7646080378c755e"
    else
      url "https://github.com/dhaam-ai/belay/releases/download/v0.1.2/belay_0.1.2_darwin_amd64.tar.gz"
      sha256 "75d51f73cb5c80fd241cde71cf71e6339e8c5412db2ea779c9d0247c3947d2f1"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/dhaam-ai/belay/releases/download/v0.1.2/belay_0.1.2_linux_arm64.tar.gz"
      sha256 "8c25c5916487856a23cac422962d9e86d390c08cc2593ab54e5381dcf04ddcdf"
    else
      url "https://github.com/dhaam-ai/belay/releases/download/v0.1.2/belay_0.1.2_linux_amd64.tar.gz"
      sha256 "0f0afdaf2633883c3fa42226a23d475c021008f44ebcb1f860423dd72ce1d54f"
    end
  end

  def install
    bin.install "belay"
  end

  def caveats
    <<~EOS
      belay drives an agent CLI; it is not one. Install Claude Code and sign in:

        https://claude.com/product/claude-code

      Then, in a repository you want it to work on:

        belay --dry-run run "add tests for the config parser"

      The dry run creates nothing and spends nothing. Drop --dry-run to start.
      belay stops at the plan for you to read before it writes any code.
    EOS
  end

  test do
    assert_match "belay version", shell_output("#{bin}/belay version")
  end
end
